name: Build Docker container

on:
  workflow_call:
    inputs:
      should_push:
        required: true
        type: boolean
    outputs:
      imageName:
        value: ${{jobs.build.outputs.imageName}}
      digest:
        value: ${{jobs.build.outputs.digest}}

jobs:
  build:
    outputs:
      imageName: ${{fromJson(steps.build-push.outputs.metadata)['image.name']}}
      digest: ${{steps.build-push.outputs.digest }}

    permissions:
      packages: write
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push Docker image
        id: build-push
        uses: docker/build-push-action@v5
        with:
          push: ${{ inputs.should_push }}
          tags: ghcr.io/${{ github.repository }}:latest
