# The "display name", shown in the GitHub UI
name: Build and test

on:
  workflow_dispatch:
  pull_request:
    branches: main

jobs:
  shared-test-workflow:
    uses: "./.github/workflows/test.reusable.yml"
